app:
  name: "StreamTail"
  version: "1.2.0"
  check_interval: 15

platforms:
  twitch:
    # from https://dev.twitch.tv/console
    enabled: true
    client_id: ""
    client_secret: ""

  youtube:
    # from https://console.cloud.google.com/
    enabled: true
    client_id: ""
    client_secret: ""

  livevk:
    # from https://dev.live.vkvideo.ru/apps
    enabled: true
    # secret key is client_secret
    client_id: ""
    client_secret: ""
    owner_id: ""

favorites:
  games:
    - "Just Chatting"
    - "Software Development"
    - "Minecraft"
    - "Dota 2"
    - "Cyberpunk 2077"
